spring:
    datasource:
        url: jdbc:mysql://localhost/vuelos_db?serverTimezone=America/Argentina/Ushuaia
        username: tasas
        password: tasas
        driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: validate
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 15MB
    mvc:
        contentnegotiation:
            favor-parameter: true
            media-types.pdf: application/pdf
        
logging:
    file:
        #path: ./logs // no se puede usar junto con file.name, uno u otro
        name: ./logs/app.log
    level:
        org:
            hibernate:
                SQL: debug 
server:
    port: ${PORT:8090} #cambio el puerto de app a 8090