insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Comandante Espora","BHI");
insert into aeropuertos (nombre, codigo) VALUES ("Aeroparque Internacional Jorge Newbery","AEP");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto El Palomar","EPA");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Ministro Pistarini","EZE");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Teniente Luis Candelaria","BRC");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Coronel Felipe Varela","CTC");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional General Enrique Mosconi","CRD");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Ingeniero Aeronáutico Ambrosio Taravella","COR");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Doctor Fernando Piragine Niveyro","CNQ");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Comandante Armando Tola","FTE");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Brigadier General Antonio Parodi","EQS");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional de Formosa","FMA");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Capitán Vicente Almandos Almonacid","IRJ");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Astor Piazzolla","MDQ");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Comodoro Ricardo Salomón","LGS");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Gobernador Francisco Gabrielli","MDZ");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Presidente Perón","NQN");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto General Justo José de Urquiza","PRA");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional de Posadas Libertador General José de San Martín","PSS");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional de Puerto Iguazú","IGR");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto El Tehuelche","PMY");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Teniente Daniel Jukic","RCQ");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional de Resistencia","RES");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Piloto Civil Norberto Fernández","RGL");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Gobernador Ramón Trejo Noel","RGA");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto de Río Cuarto","RCU");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Rosario Islas Malvinas","ROS");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional de Salta Martín Miguel de Güemes","SLA");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Domingo Faustino Sarmiento","UAQ");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Brigadier Mayor César Raúl Ojeda","LUQ");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Aeropuerto Aviador Carlos Campos, Chapelco","CPC");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Teniente Benjamín Matienzo","TUC");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Suboficial Ayudante Santiago Germano","AFA");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Gobernador Horacio Guzmán","JUJ");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto de Sauce Viejo","SFN");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto de Santa Rosa","RSA");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Vicecomodoro Ángel de la Paz Aragonés","SDE");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Termas de Río Hondo","RHD");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Almirante Marcos A. Zar","REL");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Internacional Malvinas Argentinas","USH");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto Gobernador Edgardo Castello","VDM");
insert into aeropuertos (nombre, codigo) VALUES ("Aeropuerto de Villa Gesell","VLG");